services:
  app:
    build:
      context: ../../
      dockerfile: ./stack/docker/python/Dockerfile
      target: ${DOCKER_TARGET:-base}
    env_file:
      - ../../.env
    environment:
      - PROFILE=${PROFILE}
    volumes:
      - ../../src/:/app/
      - ../../stack/logs:/app/logs
    network_mode: host
    restart: always

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ../data/ollama:/root/ollama
    env_file:
      - ../../.env
    profiles:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
