version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: ./stack/python/Dockerfile
      target: ${DOCKER_TARGET:-base}
    command: python3 main.py
    env_file:
      - ../.env
    volumes:
      - ../src/:/app/
    restart: always

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/ollama
    env_file:
      - ../.env
